---
sidebar: sidebar 
permalink: second-gen/beegfs-deploy-setting-up-an-ansible-control-node.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: Para configurar un nodo de control de Ansible, identifique una máquina virtual o física con acceso de red a los puertos de gestión de todos los nodos de archivos y bloques que puedan usarse para configurar la solución. 
---
= Configure un nodo de control Ansible
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para configurar un nodo de control de Ansible, debe designar una máquina virtual o física con acceso de red a todos los nodos de archivos y bloques que se han puesto en marcha para la solución BeeGFS en NetApp.

Consulte la link:beegfs-technology-requirements.html#ansible-control-node-requirements["Requisitos técnicos"] para obtener una lista de versiones de paquete recomendadas. Los siguientes pasos fueron probados en Ubuntu 22,04. Para conocer los pasos específicos de su distribución de Linux preferida, consulte la https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html["Documentación de Ansible"^].

. Desde el nodo de control de Ansible, instale los siguientes paquetes de entorno virtual de Python y Python.
+
[source, console]
----
sudo apt-get install python3 python3-pip python3-setuptools python3.10-venv
----
. Cree un entorno virtual de Python
+
[source, console]
----
python3 -m venv ~/pyenv
----
. Activar el entorno virtual.
+
[source, console]
----
source ~/pyenv/bin/activate
----
. Instale los paquetes de Python necesarios dentro del entorno virtual activado.
+
[source, console]
----
pip install ansible netaddr cryptography passlib
----
. Instale la colección BeeGFS con Ansible Galaxy.
+
[source, console]
----
ansible-galaxy collection install netapp_eseries.beegfs
----
. Compruebe que las versiones instaladas de Ansible, Python y la colección BeeGFS coinciden con el link:beegfs-technology-requirements.html#ansible-control-node-requirements["Requisitos técnicos"].
+
[source, console]
----
ansible --version
ansible-galaxy collection list netapp_eseries.beegfs
----
. Configure SSH sin contraseña para permitir que Ansible acceda a los nodos de archivos BeeGFS remotos desde el nodo de control Ansible.
+
.. En el nodo de control de Ansible, si es necesario, genere un par de claves públicas.
+
[source, console]
----
ssh-keygen
----
.. Configure SSH sin contraseña en cada uno de los nodos de archivo.
+
[source, console]
----
ssh-copy-id <ip_or_hostname>
----





IMPORTANT: *No* configure SSH sin contraseñas para los nodos de bloque. No se admite ni se requiere.
