---
sidebar: sidebar 
permalink: second-gen/beegfs-design-performance-tuning.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: La solución BeeGFS incluye recomendaciones para el ajuste del rendimiento basadas en pruebas de verificación. 
---
= Ajuste del rendimiento
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La solución BeeGFS incluye recomendaciones para el ajuste del rendimiento basadas en pruebas de verificación.

Si bien BeeGFS proporciona un rendimiento razonable desde el momento de su instalación, NetApp ha desarrollado un conjunto de parámetros de ajuste recomendados para maximizar el rendimiento. Estos parámetros tienen en cuenta las funcionalidades de los nodos de bloque E-Series subyacentes y todos los requisitos especiales necesarios para ejecutar BeeGFS en una arquitectura de alta disponibilidad de disco compartido.



== Ajuste del rendimiento de los nodos de archivos

Los parámetros de ajuste disponibles que puede configurar son los siguientes:

. *Configuración del sistema en el UEFI/BIOS de nodos de archivos.* para maximizar el rendimiento, recomendamos configurar los ajustes del sistema en el modelo de servidor que utilice como nodos de archivos. Los ajustes del sistema se configuran cuando se configuran los nodos de archivos mediante la configuración del sistema (UEFI/BIOS) o las API Redfish proporcionadas por el controlador de administración de la placa base (BMC).
+
La configuración del sistema varía en función del modelo de servidor que utilice como nodo de archivos. Los ajustes deben configurarse manualmente en función del modelo de servidor que se esté utilizando. Para aprender a configurar los ajustes del sistema para los nodos de archivo Lenovo SR665 validados, consulte link:beegfs-deploy-file-node-tuning.html["Ajuste la configuración del sistema del nodo de archivos para aumentar el rendimiento"].

. *Configuración predeterminada de los parámetros de configuración necesarios.* los parámetros de configuración necesarios afectan a la forma en que se configuran los servicios BeeGFS y cómo los volúmenes E-Series (dispositivos de bloques) se formatean y montan mediante Pacemaker. Entre estos parámetros de configuración necesarios se incluyen los siguientes:
+
** Parámetros de configuración del servicio BeeGFS
+
Es posible anular la configuración predeterminada para los parámetros de configuración según sea necesario. Para obtener los parámetros que puede ajustar a sus cargas de trabajo específicas o casos de uso, consulte la https://github.com/NetApp/beegfs/blob/master/roles/beegfs_ha_7_4/defaults/main.yml#L237["Parámetros de configuración del servicio BeeGFS"^].

** El formato de los volúmenes y los parámetros de montaje se establecen en los valores predeterminados recomendados y solo se deben ajustar en casos prácticos avanzados. Los valores predeterminados harán lo siguiente:
+
*** Optimización del formato de volumen inicial basado en el tipo de destino (como la gestión, los metadatos o el almacenamiento), junto con la configuración de RAID y el tamaño de segmentos del volumen subyacente.
*** Ajuste cómo monta Pacemaker cada volumen para garantizar que los cambios se vacíen inmediatamente a los nodos de bloque E-Series. De este modo se evita la pérdida de datos cuando fallan nodos de archivos con las escrituras activas en curso.
+
Para obtener los parámetros que puede ajustar a sus cargas de trabajo específicas o casos de uso, consulte la https://github.com/NetApp/beegfs/blob/master/roles/beegfs_ha_7_4/defaults/main.yml#L279["parámetros de configuración de formato de volumen y montaje"^].





. *Configuración del sistema en el sistema operativo Linux instalado en los nodos de archivos.* Puede anular la configuración predeterminada del sistema operativo Linux al crear el inventario de Ansible en el paso 4 de link:beegfs-deploy-create-inventory.html["Cree el inventario de Ansible"].
+
La configuración predeterminada se utilizó para validar BeeGFS en la solución de NetApp, pero es posible modificarla para adaptarla a sus cargas de trabajo o casos de uso específicos. Algunos ejemplos de la configuración del sistema operativo Linux que puede cambiar son los siguientes:

+
** Las colas de I/o en dispositivos de bloques E-Series.
+
Se pueden configurar colas de I/o en los dispositivos de bloque E-Series que se utilizan como destinos BeeGFS para:

+
*** Ajuste el algoritmo de programación en función del tipo de dispositivo (NVMe, HDD, etc.).
*** Aumentar el número de solicitudes pendientes.
*** Ajustar los tamaños de las solicitudes.
*** Optimice el comportamiento de lectura anticipada.


** Ajustes de memoria virtual.
+
Puede ajustar la configuración de memoria virtual para obtener un rendimiento de transmisión sostenido óptimo.

** Configuración de CPU.
+
Puede ajustar el regulador de frecuencia de la CPU y otras configuraciones de la CPU para obtener el máximo rendimiento.

** Tamaño de solicitud de lectura.
+
Puede aumentar el tamaño máximo de solicitud de lectura para las HCA de NVIDIA.







== Ajuste del rendimiento para nodos de bloques

En función de los perfiles de configuración aplicados a un bloque de creación de BeeGFS en particular, los grupos de volúmenes configurados en los nodos de bloque cambian ligeramente. Por ejemplo, con un nodo de bloque EF600 de 24 unidades:

* Para el único elemento básico, incluidos los servicios de gestión, metadatos y almacenamiento de BeeGFS:
+
** 1 grupo de volúmenes de 2+2 RAID 10 para servicios de metadatos y gestión de BeeGFS
** 2 grupos de volúmenes RAID 6 de 8+2 para servicios de almacenamiento BeeGFS


* Para un bloque básico de metadatos BeeGFS + almacenamiento:
+
** 1 grupo de volúmenes de 2+2 RAID 10 para servicios de metadatos BeeGFS
** 2 grupos de volúmenes RAID 6 de 8+2 para servicios de almacenamiento BeeGFS


* Para el almacenamiento BeeGFS, solo elemento básico:
+
** 2 grupos de volúmenes RAID 6 de 10+2 para servicios de almacenamiento BeeGFS





NOTE: Como BeeGFS necesita menos espacio de almacenamiento para la gestión y los metadatos en comparación con el almacenamiento, una opción es utilizar unidades más pequeñas para los grupos de volúmenes RAID 10. Las unidades más pequeñas deben llenarse en las ranuras de unidad más externas. Para obtener más información, consulte link:beegfs-deploy-overview.html["instrucciones de puesta en funcionamiento"].

Todos estos ajustes se configuran mediante la puesta en marcha basada en Ansible, junto con otros ajustes que suelen recomendarse para optimizar el rendimiento o el comportamiento, entre los que se incluyen:

* Ajustar el tamaño de bloque de caché global a 32 KiB y ajustar el vaciado de caché basado en demanda al 80 %.
* Al deshabilitar el equilibrio de carga automático (se garantiza que las asignaciones de volúmenes de la controladora permanezcan según la definición).
* Habilitar el almacenamiento en caché de lectura y deshabilitar el almacenamiento en caché de lectura anticipada.
* Habilitar el almacenamiento en caché de escritura con mirroring y requerir backup de batería, de modo que la caché se mantiene mediante el fallo de una controladora del nodo de bloque.
* Especificar el orden en que las unidades se asignan a grupos de volúmenes, equilibrando las operaciones de I/o en los canales de unidades disponibles.

