---
sidebar: sidebar 
permalink: second-gen/beegfs-gens.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: BeeGFS para la solución de NetApp se encuentra en su segundo diseño generacional. 
---
= Generaciones de diseño
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
BeeGFS para la solución de NetApp se encuentra en su segundo diseño generacional.

La primera y la segunda generación incluyen una arquitectura base que incorpora un sistema de archivos BeeGFS y un sistema de almacenamiento NVMe EF600. Sin embargo, la segunda generación se basa en la primera en incluir estas ventajas adicionales:

* Duplique el rendimiento y la capacidad al añadir solo 2U de espacio en rack
* Alta disponibilidad (ha) basada en un diseño de hardware de dos niveles y disco compartido
* Arquitectura diseñada para los sistemas DGX SuperPOD A100, H100, H200 y B200 de NVIDIA, que se validó previamente en un clúster de aceptación dedicado de NVIDIA. Obtenga más información sobre DGX SuperPOD de NVIDIA con NetApp en link:https://docs.netapp.com/us-en/netapp-solutions/ai/ai-dgx-superpod.html["guía de diseño"]el .




== Segundo diseño generacional

La segunda generación de BeeGFS en NetApp ha sido optimizada para satisfacer los requisitos de rendimiento de las cargas de trabajo más exigentes, como la computación de alto rendimiento (HPC), el aprendizaje automático (ML), el aprendizaje profundo (DL) y otras técnicas de inteligencia artificial (IA). Al incorporar una arquitectura de alta disponibilidad de discos compartidos, este diseño garantiza la durabilidad y la disponibilidad de los datos, lo que lo convierte en el ideal para empresas y otras organizaciones que no pueden permitirse tiempos de inactividad o pérdida de datos. El diseño de segunda generación incluye componentes como servidores PCIe Gen5 y soporte para conmutadores InfiniBand NVIDIA® Quantum™ QM9700 400GB/s. Esta solución no solo ha sido verificada por NetApp, sino que también ha superado la cualificación externa como opción de almacenamiento para el superPOD NVIDIA DGX™ A100, con una certificación ampliada para los sistemas DGX SuperPOD H100, H200 y B200.



== Primer diseño generacional

La primera generación de BeeGFS en NetApp se diseñó para cargas de trabajo de aprendizaje automático (ML) e inteligencia artificial (IA) utilizando sistemas de almacenamiento NVMe EF600 de NetApp, el sistema de archivos paralelo BeeGFS, los sistemas DGX™ A100 de NVIDIA y los switches IB NVIDIA® Mellanox® Quantum™ QM8700 200GB Gb/s. Este diseño también ofrece InfiniBand (IB) de 200GB Gb/s para la estructura de interconexión de clústeres de almacenamiento y de computación para proporcionar una arquitectura basada en IB completa para cargas de trabajo de alto rendimiento.

Para obtener más información sobre la primera generación, consulte link:https://www.netapp.com/pdf.html?item=/media/25445-nva-1156-design.pdf["IA EF-Series de NetApp con sistemas NVIDIA DGX A100 y BeeGFS"^].
