---
sidebar: sidebar 
permalink: second-gen/beegfs-technology-requirements.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: Para implementar BeeGFS en una solución NetApp, asegúrese de que su entorno cumpla los requisitos tecnológicos. 
---
= Requisitos técnicos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para implantar BeeGFS en la solución NetApp, asegúrese de que su entorno cumple los requisitos tecnológicos descritos en este documento.



== Resumen de requisitos

En esta página se detallan los requisitos de hardware, software y firmware para implementar BeeGFS en los bloques de construcción de NetApp. Los requisitos se organizan en las siguientes secciones:

* <<Requisitos de hardware>> - Nodos de archivos (hardware/software/firmware), nodos de bloques (hardware/firmware), networking y cableado
* <<Requisitos de puesta en marcha de software>> - Componentes desplegados por Ansible
* <<Requisitos del nodo de control de Ansible>> - versiones de software del nodo de control




== Requisitos de hardware

Antes de empezar, asegúrate de que tu hardware cumple las siguientes especificaciones para un diseño de bloque único de la solución BeeGFS en NetApp. Los componentes exactos para una puesta en marcha concreta pueden variar según los requisitos del cliente. Cada nodo de archivos debe cumplir o superar estas especificaciones para lograr el rendimiento esperado.



=== Requisitos del nodo de archivo

[cols="10%,90%"]
|===
| Cantidad | Especificaciones 


| 2  a| 
*Lenovo ThinkSystem SR665 V3*

*Hardware:*

* *Procesadores:* 2x AMD EPYC 9124 16C 3.0 GHz (configurados como dos zonas NUMA)
* *Memoria:* 256GB (16x 16GB TruDDR5 4800MHz RDIMM-A)
* *Expansión PCIe:* Cuatro ranuras PCIe Gen5 x16 (dos por zona NUMA)
* *Tarjetas HCA:* 4x MCX755106AS-HEAT ConnectX-7, NDR200, QSFP112, 2 puertos, PCIe Gen5 x16, InfiniBand Adapter
* *Almacenamiento:* Dos unidades en RAID 1 para OS (1TB 7.2K SATA o mejor)
* *Gestión:* puerto 1GbE para gestión en banda del sistema operativo
* *BMC:* BMC de 1GbE con API Redfish para gestión fuera de banda de servidores
* *Alimentación:* Fuentes de alimentación dobles de intercambio en caliente y ventiladores de alto rendimiento


*Software y firmware:*

* *Sistema operativo:* Red Hat 9.4 Server Physical with High Availability (2 socket)
* *Kernel de Linux:* 5.14.0-427.42.1.el9_4.x86_64
* *Firmware HCA:* FW: 28.46.1006, PXE: 3.8.0100, UEFI: 14.39.0013


|===

IMPORTANT: Los nodos de archivos requieren una suscripción válida a Red Hat Enterprise Linux Server y al Red Hat Enterprise Linux High Availability Add-On.



=== Requisitos de los nodos de bloque

Cada bloque de construcción requiere dos E-Series del mismo modelo. No mezcles modelos de E-Series dentro del mismo bloque de construcción.

[cols="10%,20%,70%"]
|===
| Cantidad | Modelo | Especificaciones 


| 2 | EF80  a| 
*Hardware:*

* *Memoria:* 128GB (64GB por controlador)
* *Adaptador:* 2x 2-port 200Gb/NDR (NVMe/IB)
* *Unidades:* Configuradas para adaptarse a los metadatos y la capacidad de almacenamiento deseada


*Firmware:*

* *SANtricity OS:* 12.00
* *NVSRAM:* NEF80-200834-D00
* *Firmware de la unidad:* Último disponible para tus modelos de unidad (consulta link:https://mysupport.netapp.com/site/downloads/firmware/e-series-disk-firmware["Sitio del firmware de un disco E-Series"^])




| 2 | EF600  a| 
*Hardware:*

* *Memoria:* 256GB (128GB por controlador)
* *Adaptador:* 2-port 200Gb/HDR (NVMe/IB)
* *Unidades:* Configuradas para adaptarse a los metadatos y la capacidad de almacenamiento deseada


*Firmware:*

* *SANtricity OS:* 11.90R5
* *NVSRAM:* N6000-890834-D02
* *Firmware de la unidad:* Último disponible para tus modelos de unidad (consulta link:https://mysupport.netapp.com/site/downloads/firmware/e-series-disk-firmware["Sitio del firmware de un disco E-Series"^])


|===


=== Requisitos del switch de red de almacenamiento

[cols="10%,90%"]
|===
| Cantidad | Especificaciones 


| 1  a| 
*Switch NVIDIA QM9700 Quantum 2 NDR InfiniBand*

El switch de red de almacenamiento debe ser capaz de 200Gb/s InfiniBand. El NVIDIA QM9700 es el switch recomendado para el cluster.

|===

NOTE: Se pueden usar switches alternativos como el NVIDIA MQM8700 Quantum, pero requieren un cableado diferente.



=== Requisitos de cableado



==== Cables de nodo de bloque a nodo de archivo

Las conexiones directas de los nodos de bloque a los nodos de archivo requieren los siguientes cables:

[cols="15%,60%,25%"]
|===
| Cantidad | Especificación del cable | Longitud 


| 8 | MCP1650-H001E30 - NVIDIA cable de cobre pasivo, QSFP56, 200Gb/s | 1 m 
|===


==== Cables de nodo de archivos a switch de almacenamiento

Se recomiendan los siguientes tipos de cable para el switch NVIDIA QM9700 Quantum 2. Elige fibra activa o cobre pasivo según lo que necesites. Las cantidades son por bloque de construcción.

[cols="20%,15%,10%,55%"]
|===
| Modelo de switch | Tipo de cable | Cantidad | Número de pieza 


.4+| NVIDIA QM9700 .3+| Fibra activa (incluidos los transceptores) | 2 | MMA4Z00-NS (multimodo, IB/ETH, 800GB Gb/s 2x400 Gb/s OSFP de dos puertos) 


| 4 | MFP7E20-Nxxx (multimodo, cable de fibra divisora de 4 canales a dos de 2 canales) 


| 8 | MMA1Z00-NS400 (multimodo, IB/ETH, un puerto QSFP-112 de 400GB Gb/s) 


| Cobre pasivo | 2 | MCP7Y40-N002 (cable divisor de cobre pasivo NVIDIA, InfiniBand 800GB/s a 4x 200GB/s, OSFP a 4x QSFP112) 
|===


=== Requisitos de puesta en marcha de software

En la siguiente tabla se enumeran los requisitos de software puestos en marcha automáticamente como parte de la puesta en marcha de BeeGFS basada en Ansible.

[cols="20%,80%"]
|===
| De NetApp | Versión 


| BeeGFS | 8.2.2 


| Corosync | 3.1.8-1 


| Marcapasos | 2.1.7-5,2 


| Agentes de valla (sepia/apc) | 4.10.0-62 


| Controladores InfiniBand/RDMA | DOCA-OFED-25.04-0.6.1 
|===


=== Requisitos del nodo de control de Ansible

BeeGFS en la solución de NetApp se pone en marcha y se gestiona desde un nodo de control de Ansible. Para obtener más información, consulte https://docs.ansible.com/ansible/latest/network/getting_started/basic_concepts.html["Documentación de Ansible"^].

Los requisitos de software que se enumeran en las siguientes tablas son específicos de la versión de la colección de Ansible BeeGFS de NetApp que se indica a continuación.

[cols="30%,70%"]
|===
| De NetApp | Versión 


| Núcleo Ansible | >= 2.19.0 


| Python | 3,12 


| Paquetes de Python adicionales | Cryptography-46.0.3, netaddr-1.3.0, ipaddr-2.2.0 


| Colección Ansible BeeGFS de NetApp E-Series | 4.0.0 
|===