---
sidebar: sidebar 
permalink: second-gen/beegfs-technology-requirements.html 
keywords: BeeGFS on NetApp, NetApp Verified Architecture, EF600 
summary: Para implementar BeeGFS en una solución NetApp, asegúrese de que su entorno cumpla los requisitos tecnológicos. 
---
= Requisitos técnicos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para implantar BeeGFS en la solución NetApp, asegúrese de que su entorno cumple los requisitos tecnológicos descritos en este documento.



== Requisitos de hardware

Antes de empezar, asegúrese de que su hardware cumpla con las siguientes especificaciones para el diseño de elementos básicos de segunda generación de la solución BeeGFS en NetApp. Los componentes exactos para una puesta en marcha concreta pueden variar en función de las necesidades del cliente.

[cols="10%,20%,70%"]
|===
| Cantidad | Componente de hardware | Requisitos 


 a| 
2
 a| 
Nodos de archivo BeeGFS
 a| 
Cada nodo de archivo debe cumplir o superar las especificaciones de los nodos de archivo recomendados para lograr el rendimiento esperado.

*Opciones de nodo de archivo recomendadas:*

* *Lenovo ThinkSystem SR665 V3*
+
** *Procesadores:* 2x AMD EPYC 9124 16C 3,0 GHz (configurado como dos zonas NUMA).
** *Memoria:* 256GB (16x 16GB TruDDR5 4800MHz RDIMM-A)
** *Expansión PCIe:* Cuatro ranuras PCIe Gen5 x16 (dos por zona NUMA)
** *Miscelánea:*
+
*** Dos unidades en RAID 1 para sistemas operativos (SATA de 1TB 7,2K TB o superior)
*** Puerto 1GbE para gestión de SO en banda
*** 1GbE BMC con API de Redfish para la gestión de servidores fuera de banda
*** Sistemas de alimentación y ventiladores de rendimiento duales intercambiables en caliente








| 2 | Nodos de bloque de E-Series (cabina EF600)  a| 
*Memoria:* 256GB (128GB por controlador). *Adaptador:* 2 puertos 200GB/HDR (NVMe/IB). *Drives:* configurado para que coincida con los metadatos deseados y la capacidad de almacenamiento.



| 8 | Adaptadores de tarjeta de host InfiniBand (para nodos de archivo).  a| 
Los adaptadores de tarjeta de host variarán según el modelo de servidor utilizado para el nodo de archivo. Las recomendaciones para los nodos de archivo verificados incluyen:

* *Servidor Lenovo ThinkSystem SR665 V3:*
+
** MCX755106AS-HEAT ConnectX-7, NDR200, QSFP112, 2 puertos, PCIe Gen5 x16, adaptador InfiniBand






| 1 | Switch de red de almacenamiento  a| 
El switch de red de almacenamiento debe tener una capacidad de velocidades InfiniBand de 200GB Gb/s. Los modelos de conmutación recomendados incluyen:

* *Interruptor NVIDIA QM9700 Quantum 2 NDR InfiniBand*
* *Interruptor NVIDIA MQM8700 Quantum HDR InfiniBand*


|===


=== Requisitos de cableado

*Conexiones directas desde nodos de bloque a nodos de archivo.*

[cols="10%,70%,20%"]
|===
| Cantidad | Número de pieza | Longitud 


| 8 | MCP1650-H001E30 (cable de cobre pasivo NVIDIA, QSFP56, 200GB/s) | 1 m 
|===
*Conexiones desde los nodos de archivos al conmutador de red de almacenamiento.* Seleccione la opción de cable adecuada de la siguiente tabla según su switch de almacenamiento InfiniBand. + La longitud del cable recomendada es de 2m m; sin embargo, esto puede variar en función del entorno del cliente.

[cols="20%,15%,10%,55%"]
|===
| Modelo de switch | Tipo de cable | Cantidad | Número de pieza 


.4+| NVIDIA QM9700 .3+| Fibra activa (incluidos los transceptores) | 2 | MMA4Z00-NS (multimodo, IB/ETH, 800GB Gb/s 2x400 Gb/s OSFP de dos puertos) 


| 4 | MFP7E20-Nxxx (multimodo, cable de fibra divisora de 4 canales a dos de 2 canales) 


| 8 | MMA1Z00-NS400 (multimodo, IB/ETH, un puerto QSFP-112 de 400GB Gb/s) 


| Cobre pasivo | 2 | MCP7Y40-N002 (cable divisor de cobre pasivo NVIDIA, InfiniBand 800GB/s a 4x 200GB/s, OSFP a 4x QSFP112) 


.2+| NVIDIA MQM8700 | Fibra activa | 8 | MFS1S00-H003E (cable de fibra activa NVIDIA, InfiniBand 200GB Gb/s, QSFP56 m) 


| Cobre pasivo | 8 | MCP1650-H002E26 (cable de cobre pasivo NVIDIA, InfiniBand 200GB Gb/s, QSFP56 m) 
|===


== Requisitos de software

Para obtener un rendimiento y una fiabilidad predecibles, los lanzamientos de BeeGFS en la solución de NetApp se prueban con versiones específicas de los componentes de software necesarios para implantar la solución.



=== Requisitos del nodo de archivo

[cols="20%,80%"]
|===
| De NetApp | Versión 


 a| 
Red Hat Enterprise Linux
 a| 
Redhat 9.3 Server físico con alta disponibilidad (2 sockets).


IMPORTANT: Los nodos de archivo requieren una suscripción válida a RedHat Enterprise Linux Server y el complemento de alta disponibilidad de Red Hat Enterprise Linux.



| Kernel de Linux | 5.14.0-362.24.1.el9_3.x86_64 


 a| 
Firmware de HCA
 a| 
*ConnectX-7 HCA Firmware* FW: 28.42.1000 + PXE: 3.7.0500 + UEFI: 14.35.0015

*ConnectX-6 HCA Firmware* FW: 20.43.1014 + PXE: 3.7.0500 + UEFI: 14.36.0016

|===


=== Requisitos del nodo de bloques de EF600

[cols="20%,80%"]
|===
| De NetApp | Versión 


| Sistema operativo SANtricity | 11.90R1 


| NVSRAM | N6000-890834-D02.dlp 


| Firmware de la unidad | La última versión disponible para los modelos de unidad en uso. 
|===


=== Requisitos de puesta en marcha de software

En la siguiente tabla se enumeran los requisitos de software puestos en marcha automáticamente como parte de la puesta en marcha de BeeGFS basada en Ansible.

[cols="20%,80%"]
|===
| De NetApp | Versión 


| BeeGFS | 7.4.4 


| Corosync | 3.1.7-1 


| Marcapasos | 2.1.6-10 


| Agentes de valla (sepia/apc) | 4.10.0-55 


| Controladores InfiniBand/RDMA | MLNX_OFED_LINUX-23,10-3,2.2,0-LTS 
|===


=== Requisitos del nodo de control de Ansible

BeeGFS en la solución de NetApp se pone en marcha y se gestiona desde un nodo de control de Ansible. Para obtener más información, consulte https://docs.ansible.com/ansible/latest/network/getting_started/basic_concepts.html["Documentación de Ansible"^].

Los requisitos de software que se enumeran en las siguientes tablas son específicos de la versión de la colección de Ansible BeeGFS de NetApp que se indica a continuación.

[cols="30%,70%"]
|===
| De NetApp | Versión 


| Ansible | 6.x cuando se instala mediante pip: Ansible-6.0.0 y ansible-core >= 2.13.0 


| Python | 3,9 (o posterior) 


| Paquetes de Python adicionales | Criptografía-43,0.0, netaddr-1,3.0, ipaddr-2.2.0 


| Colección Ansible BeeGFS de NetApp E-Series | 3.2.0 
|===