---
sidebar: sidebar 
permalink: deploy-features-integration/beegfs-csi-driver/csi-driver-prereqs.html 
keywords: BeeGFS Features, CSI, Driver 
summary: Requisitos previos para implementar el controlador CSI de BeeGFS 
---
= Requisitos previos para implementar el controlador CSI de BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Antes de implementar y configurar el controlador CSI de BeeGFS, asegúrese de tener un clúster de Kubernetes en ejecución, acceso a su clúster de BeeGFS y permisos adecuados para instalar recursos en todo el clúster.



== Verificar la configuración de Kubernetes

Ejecute el siguiente comando para verificar el estado de los pods en su clúster de Kubernetes:

[source, console]
----
kubectl get pods
----
**Resultado esperado:**

[listing]
----
root@node01:/etc/cni/net.d# kubectl get pods
No resources found in default namespace.
----
Si no hay ningún pod en ejecución, la lista estará vacía.  De lo contrario, los pods deberían aparecer enumerados sin errores.



== Validar clientes y servicios de BeeGFS

Verifique que el clúster BeeGFS esté en buen estado y que todos los servicios sean accesibles ejecutando el siguiente comando:

**BeeGFS 7.4**

[source, console]
----
beegfs-check-servers
----
**BeeGFS 8**

[source, console]
----
beegfs health check
----

NOTE: El controlador CSI funciona con ambos `beegfs-dkms-client` y `beegfs-client` , que debe instalarse en cada nodo de Kubernetes.  Para conocer los pasos de instalación, consulte la documentación de BeeGFS Client DKMS: https://doc.beegfs.io/latest/advanced_topics/client_dkms.html[]

**Resultados esperados de BeeGFS 7.4:**

[listing]
----
root@node01:/home/user_id/beegfs-csi-driver# beegfs-check-servers
Management
==========
mgmt [ID: 1]: reachable at XXX.X.AB.1:8008 (protocol: TCP)

Metadata
==========
meta_25_tgt_2501 [ID: 2501]: reachable at XXX.X.AA.MN:8255 (protocol: RDMA)
meta_26_tgt_2601 [ID: 2601]: reachable at XXX.X.BB.NO:8265 (protocol: RDMA)
meta_27_tgt_2701 [ID: 2701]: reachable at XXX.X.AA.OP:8275 (protocol: RDMA)
meta_28_tgt_2801 [ID: 2801]: reachable at XXX.X.BB.PQ:8285 (protocol: RDMA)
meta_29_tgt_2901 [ID: 2901]: reachable at XXX.X.AA.QR:8295 (protocol: RDMA)
meta_30_tgt_3001 [ID: 3001]: reachable at XXX.X.BB.RS:8305 (protocol: RDMA)
meta_31_tgt_3101 [ID: 3101]: reachable at XXX.X.AA.ST:8315 (protocol: RDMA)
meta_32_tgt_3201 [ID: 3201]: reachable at XXX.X.BB.TU:8325 (protocol: RDMA)

Storage
==========
stor_25_tgt_2501 [ID: 2501]: reachable at XXX.X.CC.MN:8253 (protocol: RDMA)
stor_26_tgt_2601 [ID: 2601]: reachable at XXX.X.DD.NO:8263 (protocol: RDMA)
stor_27_tgt_2701 [ID: 2701]: reachable at XXX.X.CC.OP:8273 (protocol: RDMA)
stor_28_tgt_2801 [ID: 2801]: reachable at XXX.X.DD.PQ:8283 (protocol: RDMA)
stor_29_tgt_2901 [ID: 2901]: reachable at XXX.X.CC.QR:8293 (protocol: RDMA)
stor_30_tgt_3001 [ID: 3001]: reachable at XXX.X.DD.RS:8303 (protocol: RDMA)
stor_31_tgt_3101 [ID: 3101]: reachable at XXX.X.CC.ST:8313 (protocol: RDMA)
stor_32_tgt_3201 [ID: 3201]: reachable at XXX.X.DD.32:8323 (protocol: RDMA)
----
Si no se puede acceder a algún servicio, asegúrese de que el cliente BeeGFS esté configurado correctamente y de que la conectividad de red a los servidores BeeGFS funcione.
