---
sidebar: sidebar 
permalink: deploy-features-integration/beegfs-csi-driver/csi-driver-verify.html 
keywords: BeeGFS Features, CSI, Driver 
summary: Verificación de la implementación del controlador CSI de BeeGFS. 
---
= Verificación de la implementación del controlador CSI de BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para verificar que el controlador CSI de BeeGFS se haya implementado correctamente, verifique el estado de los pods del controlador CSI y confirme que se estén ejecutando como se esperaba.

Para comprobar el estado de todos los recursos en el espacio de nombres BeeGFS-CSI, ejecute:

[source, console]
----
kubectl get all -n beegfs-csi
----
**Resultado esperado:**

[listing]
----
NAME                          READY    STATUS      RESTARTS    AGE
pod/csi-beegfs-controller-0   3/3      Running     0           5d11h
pod/csi-beegfs-node-8f917     3/3      Running     0           5d11h
----


== Inspeccionar el módulo del controlador

Para diagnosticar problemas o recopilar más detalles sobre el pod del controlador CSI de BeeGFS, utilice el siguiente comando para describir el pod y revisar sus eventos, estado y actividad reciente:

[source, console]
----
kubectl describe pod csi-beegfs-controller-0 -n beegfs-csi
----
**Resultado esperado:**

[listing]
----
Events:

  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  117s                 default-scheduler  Successfully assigned beegfs-csi/csi-beegfs-controller-0 to node01
  Normal   Pulled     117s                 kubelet            Container image "registry.k8s.io/sig-storage/csi-provisioner:v3.5.0" already present on machine
  Normal   Created    117s                 kubelet            Created container: csi-provisioner
  Normal   Started    117s                 kubelet            Started container csi-provisioner
  Normal   Started    101s (x3 over 117s)  kubelet            Started container beegfs
  Normal   Pulled     86s (x2 over 117s)   kubelet            Container image "registry.k8s.io/sig-storage/csi-resizer:v1.11.1" already present on machine
  Normal   Created    86s (x2 over 117s)   kubelet            Created container: csi-resizer
  Normal   Started    86s (x2 over 117s)   kubelet            Started container csi-resizer
  Warning  BackOff    85s (x5 over 115s)   kubelet            Back-off restarting failed container beegfs in pod csi-beegfs-controller-0_beegfs-csi(47016fd3-3a2a-41ed-bc4c-5a716c377b1e)
  Normal   Pulled     73s (x4 over 117s)   kubelet            Container image "ghcr.io/thinkparq/beegfs-csi-driver:v1.7.0" already present on machine
  Normal   Created    73s (x4 over 117s)   kubelet            Created container: beegfs
----


== Verificar StorageClass

. Validar que StorageClass se haya creado exitosamente:
+
[source, console]
----
kubectl get sc
----
+
**Resultado esperado:**

+
[listing]
----
root@node01:/home/user_id/beegfs-csi-driver# kubectl get sc
NAME                PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
csi-beegfs-dyn-sc   beegfs.csi.org.com   Delete          Immediate           true                   17s
----
. Confirme que el volumen BeeGFS esté montado como se esperaba.
+
Verificar el directorio especificado como `volDirBasePath` en `examples/k8s/dyn/dyn-sc.yaml` aparece debajo `/mnt/beegfs` .

+
Por ejemplo, si `volDirBasePath` está configurado para `user_id_k8s` Deberías ver este directorio en la lista:

+
[source, console]
----
root@node01:/# ls -ltr /mnt/beegfs/
total 1
drwxrwxrwx 4 root root 2 Oct 15 10:16 user_id_k8s
----

