---
sidebar: sidebar 
permalink: administer/clusters-upgrade-beegfs.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, update, upgrade 
summary: Use Ansible para actualizar BeeGFS y el clúster de alta disponibilidad. 
---
= Actualizar los servicios BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Usa Ansible para actualizar la versión de BeeGFS que se ejecuta en tu clúster de HA.



== Descripción general

BeeGFS sigue un `major.minor.patch` esquema de control de versiones. Se proporcionan los roles de Ansible de alta disponibilidad de BeeGFS para cada `major.minor` versión compatible (p. ej., `beegfs_ha_7_2` y `beegfs_ha_7_3`). Todos los roles de alta disponibilidad se fijan a la última versión de parche de BeeGFS disponible en el momento del lanzamiento de la colección Ansible.

Ansible se debe usar para todas las actualizaciones de BeeGFS, incluyendo el cambio entre versiones principales, menores y de parches de BeeGFS. Para actualizar BeeGFS primero necesitas actualizar la colección BeeGFS Ansible, lo que también traerá las últimas correcciones y mejoras en la automatización de despliegue/gestión y el clúster HA subyacente. Incluso después de actualizar a la última versión de la colección, BeeGFS no se actualizará hasta que se ejecute `ansible-playbook` con la opción `-e "beegfs_ha_force_upgrade=true"` activada. Para más detalles sobre cada actualización, consulta la link:https://doc.beegfs.io/latest/advanced_topics/upgrade.html["Documentación de actualización de BeeGFS"^] para tu versión actual.


NOTE: Si estás actualizando a BeeGFS 8, consulta el procedimiento link:clusters-upgrade-beegfs-v8.html["Actualiza a BeeGFS 8"] en su lugar.



== Rutas de actualización probadas

Se han probado y verificado las siguientes rutas de actualización:

[cols="1,1,1,5"]
|===
| Versión original | Actualizar la versión | MultiRail | Detalles 


| 7.2.6 | 7.3.2 | Sí | Actualización de la colección beegfs de v3.0.1 a v3.1.0, multirail agregó 


| 7.2.6 | 7.2.8 | No | Actualizando la colección beegfs de v3.0.1 a v3.1.0 


| 7.2.8 | 7.3.1 | Sí | Actualización mediante la colección beegfs v3.1.0, multirail añadido 


| 7.3.1 | 7.3.2 | Sí | Actualice utilizando beegfs Collection v3.1.0 


| 7.3.2 | 7.4.1 | Sí | Actualice utilizando beegfs Collection v3.2.0 


| 7.4.1 | 7.4.2 | Sí | Actualice utilizando beegfs Collection v3.2.0 


| 7.4.2 | 7.4.6 | Sí | Actualice utilizando beegfs Collection v3.2.0 


| 7.4.6 | 8,0 | Sí | Actualiza usando las instrucciones en el procedimiento link:clusters-upgrade-beegfs-v8.html["Actualiza a BeeGFS 8"]. 


| 7.4.6 | 8,1 | Sí | Actualiza usando las instrucciones en el procedimiento link:clusters-upgrade-beegfs-v8.html["Actualiza a BeeGFS 8"]. 


| 7.4.6 | 8,2 | Sí | Actualiza usando las instrucciones en el procedimiento link:clusters-upgrade-beegfs-v8.html["Actualiza a BeeGFS 8"]. 
|===


== Pasos de actualización de BeeGFS

En las siguientes secciones se ofrecen pasos para actualizar la colección Ansible BeeGFS y el propio BeeGFS. Preste especial atención a cualquier paso(s) adicional(s) para actualizar BeeGFS versiones mayores o menores.



=== Paso 1: Actualizar la colección BeeGFS

Para actualizaciones de colecciones con acceso a. link:https://galaxy.ansible.com/netapp_eseries/beegfs["Galaxia de ansible"^], ejecute el siguiente comando:

[source, console]
----
ansible-galaxy collection install netapp_eseries.beegfs --upgrade
----
Para actualizaciones de colecciones sin conexión, descargue la colección desde link:https://galaxy.ansible.com/netapp_eseries/beegfs["Galaxia de ansible"^] haciendo clic en el deseado `Install Version`` y después `Download tarball`. Transfiera el tarball al nodo de control de Ansible y ejecute el siguiente comando.

[source, console]
----
ansible-galaxy collection install netapp_eseries-beegfs-<VERSION>.tar.gz --upgrade
----
Consulte link:https://docs.ansible.com/ansible/latest/collections_guide/collections_installing.html["Instalando colecciones"^] si quiere más información.



=== Paso 2: Actualice el inventario de Ansible

Haz cualquier actualización necesaria o que quieras en los archivos de inventario de Ansible de tu clúster. Mira la sección <<Notas de actualización de la versión>> abajo para ver detalles sobre tus requisitos específicos de actualización. Mira la sección link:../custom/architectures-inventory-overview.html["Descripción general del inventario de Ansible"^] para información general sobre cómo configurar tu inventario de BeeGFS HA.



=== Paso 3: Actualizar Ansible playbook (cuando se actualizan solo versiones principales o secundarias)

Si va a cambiar entre versiones principal o secundaria, en `playbook.yml` el archivo usado para implementar y mantener el clúster, actualice el nombre `beegfs_ha_<VERSION>` del rol para reflejar la versión deseada. Por ejemplo, si desea desplegar BeeGFS 7,4, esto sería `beegfs_ha_7_4`:

[source, yaml]
----
- hosts: all
  gather_facts: false
  any_errors_fatal: true
  collections:
    - netapp_eseries.beegfs
  tasks:
    - name: Ensure BeeGFS HA cluster is setup.
      ansible.builtin.import_role:  # import_role is required for tag availability.
        name: beegfs_ha_7_4
----
Si desea obtener más información sobre el contenido de este archivo de playbook, consulte link:../custom/architectures-deploy-ha-cluster.html["Ponga en marcha el clúster de alta disponibilidad de BeeGFS"^]la sección.



=== Paso 4: Ejecute la actualización de BeeGFS

Para aplicar la actualización de BeeGFS:

[source, console]
----
ansible-playbook -i inventory.yml beegfs_ha_playbook.yml -e "beegfs_ha_force_upgrade=true" --tags beegfs_ha
----
Entre bastidores, el rol de BeeGFS ha se encargará de:

* Asegúrese de que el clúster esté en estado óptimo en cada servicio BeeGFS ubicado en su nodo preferido.
* Ponga el clúster en modo de mantenimiento.
* Actualice los componentes del clúster de alta disponibilidad (si es necesario).
* Actualice cada nodo de archivo de uno en uno de los siguientes modos:
+
** Colóquela en espera y realice la conmutación al nodo de respaldo de sus servicios en el nodo secundario.
** Actualizar paquetes BeeGFS.
** Servicios de respaldo.


* Mueva el clúster fuera del modo de mantenimiento.




== Notas de actualización de la versión



=== Actualización desde BeeGFS versión 7.2.6 o 7.3.0



==== Cambios en la autenticación basada en conexión

BeeGFS versión 7.3.2 y posteriores requieren que se configure la autenticación basada en conexión. Los servicios no se iniciarán sin una de las siguientes opciones:

* Especificar un `connAuthFile`, o
* Configuración `connDisableAuthentication=true` en el archivo de configuración del servicio.


Se recomienda encarecidamente activar la autenticación basada en conexión por seguridad. Consulta link:https://doc.beegfs.io/7.3.2/advanced_topics/authentication.html#connectionbasedauth["Autenticación basada en conexión BeeGFS"^] para más información.

Los `beegfs_ha*` roles generan y distribuyen automáticamente el archivo de autenticación a:

* Todos los nodos de archivos en el clúster
* El nodo de control de Ansible en `<playbook_directory>/files/beegfs/<beegfs_mgmt_ip_address>_connAuthFile`


La `beegfs_client` función detectará y aplicará automáticamente este archivo a los clientes cuando esté presente.


WARNING: Si no usaste el rol `beegfs_client` para configurar clientes, debes distribuir manualmente el archivo de autenticación a cada cliente y configurar la opción `connAuthFile` en el archivo `beegfs-client.conf`. Al actualizar desde una versión de BeeGFS sin autenticación basada en conexión, los clientes perderán el acceso a menos que desactives la autenticación basada en conexión durante la actualización configurando `beegfs_ha_conn_auth_enabled: false` en `group_vars/ha_cluster.yml` (no recomendado).

Para más detalles y opciones de configuración alternativas, consulta el paso de configuración de autenticación de la conexión en la sección link:../custom/architectures-inventory-common-file-node-configuration.html["Especifique la configuración de nodos de archivos comunes"^].
