---
sidebar: sidebar 
permalink: administer/clusters-reconfigure.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, Ansible, pcs 
summary: Use Ansible para volver a configurar el clúster. 
---
= Vuelva a configurar el clúster de alta disponibilidad y BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Use Ansible para volver a configurar el clúster.



== Descripción general

Normalmente, la reconfiguración de cualquier aspecto del clúster de alta disponibilidad de BeeGFS se debe realizar actualizando `ansible-playbook` el inventario de Ansible y volviendo a ejecutar el comando. Esto incluye la actualización de alertas, el cambio de la configuración permanente de la vallado o el ajuste de la configuración del servicio BeeGFS. Estos se ajustan utilizando el `group_vars/ha_cluster.yml` archivo y se puede encontrar una lista completa de opciones en la link:../custom/architectures-inventory-common-file-node-configuration.html["Especifique la configuración de nodos de archivos comunes"^] sección.

Consulte a continuación para obtener más información sobre opciones de configuración seleccionadas que los administradores deben conocer al realizar tareas de mantenimiento o mantenimiento del clúster.



== Cómo deshabilitar y activar delimitación

La cercado se habilita o requiere de forma predeterminada cuando se configura el clúster. En algunos casos, puede que sea conveniente desactivar temporalmente la delimitación para garantizar que los nodos no se cierren accidentalmente al realizar determinadas operaciones de mantenimiento (como la actualización del sistema operativo). Aunque esto se puede desactivar manualmente, hay sacrificios que los administradores deben tener en cuenta.



=== OPCIÓN 1: Desactive la esgrima con Ansible (recomendado).

Cuando se desactiva el cercado mediante Ansible, la acción en caso de fallo del monitor BeeGFS cambia de "cerca" a "en espera". Esto significa que si el monitor BeeGFS detecta un fallo, intentará poner el nodo en espera y realizar una conmutación por error de todos los servicios de BeeGFS. Fuera de la solución activa de problemas/pruebas esto es normalmente más deseable que la opción 2. La desventaja es que si un recurso no se detiene en el nodo original, se impedirá que se inicie en otro lugar (por lo que normalmente se requiere cercado para los clústeres de producción).

. En su inventario de Ansible en `groups_vars/ha_cluster.yml` añada la siguiente configuración:
+
[source, console]
----
beegfs_ha_cluster_crm_config_options:
    stonith-enabled: False
----
. Vuelva a ejecutar el libro de estrategia de Ansible para aplicar los cambios al clúster.




=== OPCIÓN 2: Desactive la delimitación manualmente.

En algunos casos puede que desee deshabilitar temporalmente la delimitación sin volver a leer Ansible, quizás para facilitar la solución de problemas o las pruebas del clúster.


WARNING: En esta configuración si el monitor BeeGFS detecta un error, el clúster intentará detener el grupo de recursos correspondiente. NO activará una conmutación por error completa ni intentará reiniciar ni mover el grupo de recursos afectado a otro host. Para recuperarse, solucione cualquier problema que se pueda ejecutar `pcs resource cleanup` o coloque manualmente el nodo en espera.

Pasos:

. Para determinar si el cercado (stonith) está habilitado o desactivado globalmente, ejecute: `pcs property show stonith-enabled`
. Para desactivar la secuencia de cercado: `pcs property set stonith-enabled=false`
. Para habilitar la ejecución de cercado: `pcs property set stonith-enabled=true`


Nota: Este ajuste se anulará la próxima vez que ejecute la tableta Ansible playbook.
