---
sidebar: sidebar 
permalink: administer/clusters-ansible-pcs.html 
keywords: BeeGFS on NetApp, HA, Cluster, Administration, pcs, Ansible 
summary: ¿Cuándo debe utilizar Ansible frente a la herramienta de línea de comandos de pc para gestionar el clúster de alta disponibilidad? 
---
= Cuándo usar Ansible frente a la herramienta pc
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
¿Cuándo debe utilizar Ansible frente a la herramienta de línea de comandos de pc para gestionar el clúster de alta disponibilidad?

Todas las tareas de puesta en marcha y reconfiguración del clúster se deben completar con Ansible desde un nodo de control externo de Ansible. Normalmente, los cambios temporales en el estado del clúster (por ejemplo, la colocación de nodos dentro y fuera de espera) se realizarán iniciando sesión en un nodo del clúster (preferiblemente uno que no esté degradado o esté a punto de someterse a tareas de mantenimiento) y utilizando la herramienta de línea de comandos del pc.

La modificación de cualquier configuración del clúster, incluidos los recursos, las restricciones, las propiedades y los propios servicios de BeeGFS, siempre debe realizarse con Ansible. Mantener una copia actualizada del inventario y el libro de estrategia de Ansible (lo ideal para un control de origen para realizar un seguimiento de los cambios) forma parte del mantenimiento del clúster. Si necesita realizar cambios en la configuración, actualice el inventario y vuelva a ejecutar el libro de aplicaciones de Ansible que importa el rol de alta disponibilidad de BeeGFS.

El rol de alta disponibilidad manejará colocar el clúster en modo de mantenimiento y, a continuación, hará los cambios necesarios antes de reiniciar BeeGFS o los servicios de clúster para aplicar la nueva configuración. Dado que normalmente no es necesario reiniciar el nodo completo fuera de la puesta en marcha inicial, Ansible se considera un procedimiento "seguro", pero siempre es un procedimiento recomendado durante las ventanas de mantenimiento o fuera de las horas, en caso de que se deban reiniciar los servicios de BeeGFS. Normalmente, estos reinicios no deben causar errores en la aplicación, pero pueden afectar al rendimiento (que algunas aplicaciones pueden manejar mejor que otras).

La repetición de la operación de Ansible también es una opción cuando desea devolver todo el clúster a un estado completamente óptimo y, en algunos casos, puede recuperar el estado del clúster con más facilidad que con los pc. Especialmente durante una emergencia en la que el clúster está inactivo por algún motivo, una vez que todos los nodos se vuelven a ejecutar Ansible puede recuperar el clúster de forma más rápida y fiable que intentar usar los pc.
