---
sidebar: sidebar 
permalink: custom/architectures-setup-nodes.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: Pasos manuales necesarios para configurar nodos de archivos y bloques antes de ejecutar Ansible. 
---
= Configure los nodos de archivos y bloques
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Pasos manuales necesarios para configurar nodos de archivos y bloques antes de ejecutar Ansible.



== Nodos de archivos



=== Configurar el controlador de administración de la placa base (BMC)

Un controlador de administración en placa base (BMC), conocido a veces como procesador de servicios, es el nombre genérico para la capacidad de administración fuera de banda integrada en varias plataformas de servidor que pueden proporcionar acceso remoto aunque el sistema operativo no esté instalado o sea accesible. Los proveedores suelen comercializar esta funcionalidad con su propia Marca. Por ejemplo, en el Lenovo SR665, el BMC se conoce como controlador XClaridad Lenovo (XCC).

Siga la documentación del proveedor del servidor para habilitar las licencias necesarias para acceder a esta funcionalidad y asegurarse de que el BMC está conectado a la red y configurado de forma adecuada para el acceso remoto.


NOTE: Si desea utilizar la cercado basada en BMC con Redfish, asegúrese de que Redfish esté activado y de que se pueda acceder a la interfaz BMC desde el sistema operativo instalado en el nodo de archivo. Es posible que se requiera una configuración especial en el conmutador de red si el BMC y el sistema operativo comparten la misma interfaz de red física.



=== Ajuste la configuración del sistema

Utilizando la interfaz de configuración del sistema (BIOS/UEFI), asegúrese de que los ajustes se han establecido para maximizar el rendimiento. La configuración exacta y los valores óptimos variarán en función del modelo de servidor que se esté utilizando. Se proporciona orientación para link:../second-gen/beegfs-deploy-file-node-tuning.html["modelos de nodos de archivos verificados"^], de lo contrario, consulte la documentación del proveedor del servidor y las mejores prácticas basadas en su modelo.



=== Instale un sistema operativo

Instale un sistema operativo compatible basado en los requisitos de nodo de archivo que se muestran link:../second-gen/beegfs-technology-requirements.html#file-node-requirements["aquí"^]. Consulte los pasos adicionales que se indican a continuación según su distribución de Linux.



==== Red Hat

Utilice RedHat Subscription Manager para registrar y suscribirse al sistema para permitir la instalación de los paquetes necesarios desde los repositorios oficiales de Red Hat y para limitar las actualizaciones a la versión compatible de Red Hat: `subscription-manager release --set=<MAJOR_VERSION>.<MINOR_VERSION>`. Para ver instrucciones, consulte https://access.redhat.com/solutions/253273["Cómo registrar y suscribirse a un sistema RHEL"^] y..  https://access.redhat.com/solutions/2761031["Cómo limitar las actualizaciones"^].

Active el repositorio de Red Hat que contiene los paquetes necesarios para la alta disponibilidad:

....
subscription-manager repo-override --repo=rhel-9-for-x86_64-highavailability-rpms --add=enabled:1
....


=== Configure la red de gestión

Configure las interfaces de red necesarias para permitir la administración en banda del sistema operativo. Los pasos exactos dependerán de la distribución y versión específicas de Linux que se esté utilizando.


NOTE: Compruebe que SSH esté habilitado y que todas las interfaces de gestión sean accesibles desde el nodo de control de Ansible.



=== Actualice el firmware de HCA y HBA

Asegúrese de que todos los HBA y HCA están ejecutando las versiones de firmware compatibles enumeradas en link:https://imt.netapp.com/matrix/["Matriz de interoperabilidad de NetApp"^]y, si es necesario, actualícelos. Se pueden encontrar recomendaciones adicionales para los adaptadores NVIDIA ConnectX link:../second-gen/beegfs-technology-requirements.html#file-node-requirements["aquí"^].



== Nodos de bloques

Siga los pasos a. link:https://docs.netapp.com/us-en/e-series/getting-started/getup-run-concept.html["Póngase en marcha con E-Series"^] para configurar el puerto de gestión en cada controladora del nodo de bloque y, opcionalmente, establezca el nombre de la cabina de almacenamiento para cada sistema.


NOTE: No será necesario realizar ninguna configuración adicional más allá de garantizar que todos los nodos de bloques sean accesibles desde el nodo de control de Ansible. La configuración del sistema restante se aplicará/mantendrá con Ansible.
