---
sidebar: sidebar 
permalink: custom/architectures-plan-file-system.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: Planifique la puesta en marcha del sistema de archivos antes de crear el inventario de Ansible. 
---
= Planifique el sistema de archivos
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Planifique la puesta en marcha del sistema de archivos antes de crear el inventario de Ansible.



== Descripción general

Antes de implementar el sistema de archivos, debe definir qué direcciones IP, puertos y otra configuración serán necesarias para todos los nodos de archivos, nodos de bloques y servicios BeeGFS que se ejecuten en el clúster. Aunque la configuración exacta variará en función de la arquitectura del clúster, esta sección define las prácticas recomendadas y los pasos a seguir que son aplicables.



== Pasos

. Si utiliza un protocolo de almacenamiento basado en IP (como Iser, iSCSI, NVMe/IB o NVMe/roce) para conectar nodos de archivos a nodos de bloques, rellene la siguiente hoja de datos para cada elemento básico. Cada conexión directa en un único bloque de creación debería tener una subred única y no debería haber superposición con subredes utilizadas para la conectividad cliente-servidor.
+
|===


| Nodo de archivo | Puerto IB | Dirección IP | Nodo de bloques | Puerto IB | IP física | Virtual IP (solo para EF600 con HDR IB) 


| <HOSTNAME> | <PORT> | <IP/SUBNET> | <HOSTNAME> | <PORT> | <IP/SUBNET> | <IP/SUBNET> 
|===
+

NOTE: Si los nodos de archivo y bloque de cada bloque de creación están conectados directamente, a menudo puede reutilizar las mismas IP/esquema para varios bloques de creación.

. Independientemente de si utiliza InfiniBand o RDMA sobre Ethernet convergente (roce) para la red de almacenamiento, rellene la siguiente hoja de datos para determinar los rangos de IP que se usarán para los servicios de clúster de alta disponibilidad, los servicios de archivos BeeGFS y los clientes para comunicarse:
+
|===
| Específico | Puerto InfiniBand | Dirección IP o rango 


| IP(s) de clúster de BeeGFS | <INTERFACE(s)> | <RANGE> 


| Gestión de BeeGFS | <INTERFACE(s)> | <IP(s)> 


| Metadatos de BeeGFS | <INTERFACE(s)> | <RANGE> 


| Almacenamiento de BeeGFS | <INTERFACE(s)> | <RANGE> 


| Clientes BeeGFS | <INTERFACE(s)> | <RANGE> 
|===
+
.. Si utiliza una sola subred IP, solo será necesaria una hoja de datos; de lo contrario, rellene también una hoja de cálculo para la segunda subred.


. En función de lo anterior, para cada bloque de creación del clúster, rellene la siguiente hoja de trabajo que define qué servicios de BeeGFS se ejecutará. Para cada servicio, especifique los nodos de archivo preferidos/secundarios, el puerto de red, las IP flotantes, la asignación de zonas NUMA (si es necesario) y qué nodos de bloque se usarán para sus destinos. Consulte las siguientes directrices al rellenar la hoja de trabajo:
+
.. Especifique los servicios BeeGFS como cualquiera de los dos `mgmt.yml`, `meta_<ID>.yml`, o. `storage_<ID>.yml` Donde ID representa un número único en todos los servicios BeeGFS de ese tipo en este sistema de archivos. Esta convención simplificará la referencia a esta hoja de trabajo en secciones posteriores mientras crea archivos para configurar cada servicio.
.. Los puertos para los servicios BeeGFS sólo deben ser únicos en un bloque de construcción en particular. Asegúrese de que los servicios con el mismo número de puerto no pueden ejecutarse nunca en el mismo nodo de archivo para evitar conflictos de puertos.
.. Si los servicios necesarios pueden utilizar volúmenes de más de un nodo de bloque o un pool de almacenamiento (y no todos los volúmenes deben ser propiedad de la misma controladora). Múltiples servicios también pueden compartir la misma configuración de nodo de bloque o pool de almacenamiento (se definirán los volúmenes individuales en una sección posterior).
+
|===
| Servicio BeeGFS (nombre de archivo) | Nodos de archivos | Puerto | IP flotantes | Zona NUMA | Nodo de bloques | Del banco de almacenamiento | Controladora propietaria 


| <SERVICE TYPE>_<ID>.yml | <PREFERRED FILE NODE> <SECONDARY FILE NODE(s)> | <PORT> | <INTERFACE>:<IP/SUBNET> <INTERFACE>:<IP/SUBNET> | <NUMA NODE/ZONE> | <BLOCK NODE> | <STORAGE POOL/VOLUME GROUP> | <A OR B> 
|===




Para obtener más información sobre las convenciones estándar, las mejores prácticas y las hojas de trabajo completadas de ejemplo, consulte link:../second-gen/beegfs-deploy-bestpractice.html["mejores prácticas"^]link:../second-gen/beegfs-deploy-define-inventory.html["Defina los bloques de creación de BeeGFS"^]las secciones y de la arquitectura verificada de BeeGFS en NetApp.
