---
sidebar: sidebar 
permalink: custom/architectures-inventory-configure-block-nodes.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: 'Especifique la configuración de los nodos de bloque individuales con variables de host (host_var).' 
---
= Configure nodos de bloques individuales
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Especifique la configuración de los nodos de bloque individuales con variables de host (host_var).



== Descripción general

Esta sección recorre la relleno de un `host_vars/<BLOCK_NODE_HOSTNAME>.yml` archivo de cada nodo de bloque del clúster. Estos archivos sólo deben contener una configuración exclusiva de un nodo de bloque determinado. Esto incluye normalmente:

* El nombre del sistema (como se muestra en System Manager).
* La URL de HTTPS para una de las controladoras (se utiliza para gestionar el sistema mediante su API DE REST).
* Qué nodos de archivo de protocolo de almacenamiento utilizan para conectarse a este nodo de bloque.
* Configurar los puertos de tarjeta de interfaz del host (HIC), como las direcciones IP (si son necesarias).




== Pasos

Haciendo referencia al esquema de direcciones IP definido en la link:architectures-plan-file-system.html["Planifique el sistema de archivos"^] sección, para cada nodo de bloque del cluster cree un archivo `host_vars/<BLOCK_NODE_HOSTNAME>/yml` y rellénelo de la siguiente manera:

. En la parte superior, especifique el nombre del sistema y la URL de HTTPS para una de las controladoras:
+
[source, yaml]
----
eseries_system_name: <SYSTEM_NAME>
eseries_system_api_url: https://<MANAGEMENT_HOSTNAME_OR_IP>:8443/devmgr/v2/
----
. Seleccione la link:https://github.com/netappeseries/santricity/tree/release-1.3.1/roles/nar_santricity_host#role-variables["protocolo"^] los nodos de archivo utilizarán para conectarse a este nodo de bloque:
+
.. Protocolos compatibles: `auto`, `iscsi`, `fc`, `sas`, `ib_srp`, `ib_iser`, `nvme_ib`, `nvme_fc`, `nvme_roce`.
+
[source, yaml]
----
eseries_initiator_protocol: <PROTOCOL>
----


. Según el protocolo en uso, los puertos HIC pueden necesitar una configuración adicional. Si es necesario, se debe definir la configuración de puertos de HIC para que la entrada superior de la configuración de cada controladora se corresponda con el puerto físico más a la izquierda de cada controladora y el puerto inferior al puerto que se encuentra en el extremo derecho. Todos los puertos requieren una configuración válida incluso si no están en uso actualmente.
+

IMPORTANT: Consulte también la siguiente sección si utiliza InfiniBand HDR (200 GB) o roce de 200 GB con nodos de bloque EF600.

+
.. Para iSCSI:
+
[source, yaml]
----
eseries_controller_iscsi_port:
  controller_a:         # Ordered list of controller A channel definition.
    - state:            # Whether the port should be enabled. Choices: enabled, disabled
      config_method:    # Port configuration method Choices: static, dhcp
      address:          # Port IPv4 address
      gateway:          # Port IPv4 gateway
      subnet_mask:      # Port IPv4 subnet_mask
      mtu:              # Port IPv4 mtu
    - (...)             # Additional ports as needed.
  controller_b:         # Ordered list of controller B channel definition.
    - (...)             # Same as controller A but for controller B

# Alternatively the following common port configuration can be defined for all ports and omitted above:
eseries_controller_iscsi_port_state: enabled         # Generally specifies whether a controller port definition should be applied Choices: enabled, disabled
eseries_controller_iscsi_port_config_method: dhcp    # General port configuration method definition for both controllers. Choices: static, dhcp
eseries_controller_iscsi_port_gateway:               # General port IPv4 gateway for both controllers.
eseries_controller_iscsi_port_subnet_mask:           # General port IPv4 subnet mask for both controllers.
eseries_controller_iscsi_port_mtu: 9000              # General port maximum transfer units (MTU) for both controllers. Any value greater than 1500 (bytes).

----
.. Para Iser:
+
[source, yaml]
----
eseries_controller_ib_iser_port:
  controller_a:    # Ordered list of controller A channel address definition.
    -              # Port IPv4 address for channel 1
    - (...)        # So on and so forth
  controller_b:    # Ordered list of controller B channel address definition.
----
.. Para NVMe/IB:
+
[source, yaml]
----
eseries_controller_nvme_ib_port:
  controller_a:    # Ordered list of controller A channel address definition.
    -              # Port IPv4 address for channel 1
    - (...)        # So on and so forth
  controller_b:    # Ordered list of controller B channel address definition.
----
.. Para NVMe/roce:
+
[source, yaml]
----
eseries_controller_nvme_roce_port:
  controller_a:         # Ordered list of controller A channel definition.
    - state:            # Whether the port should be enabled.
      config_method:    # Port configuration method Choices: static, dhcp
      address:          # Port IPv4 address
      subnet_mask:      # Port IPv4 subnet_mask
      gateway:          # Port IPv4 gateway
      mtu:              # Port IPv4 mtu
      speed:            # Port IPv4 speed
  controller_b:         # Ordered list of controller B channel definition.
    - (...)             # Same as controller A but for controller B

# Alternatively the following common port configuration can be defined for all ports and omitted above:
eseries_controller_nvme_roce_port_state: enabled         # Generally specifies whether a controller port definition should be applied Choices: enabled, disabled
eseries_controller_nvme_roce_port_config_method: dhcp    # General port configuration method definition for both controllers. Choices: static, dhcp
eseries_controller_nvme_roce_port_gateway:               # General port IPv4 gateway for both controllers.
eseries_controller_nvme_roce_port_subnet_mask:           # General port IPv4 subnet mask for both controllers.
eseries_controller_nvme_roce_port_mtu: 4200              # General port maximum transfer units (MTU). Any value greater than 1500 (bytes).
eseries_controller_nvme_roce_port_speed: auto            # General interface speed. Value must be a supported speed or auto for automatically negotiating the speed with the port.
----
.. Los protocolos FC y SAS no requieren configuración adicional. SRP no se recomienda correctamente.




Para obtener opciones adicionales para configurar los puertos HIC y los protocolos de host, incluida la capacidad de configurar CHAP iSCSI, consulte la link:https://github.com/netappeseries/santricity/tree/release-1.3.1/roles/nar_santricity_host#role-variables["documentación"^] Incluido con la colección SANtricity. Tenga en cuenta que al implementar BeeGFS, el pool de almacenamiento, la configuración de volumen y otros aspectos del aprovisionamiento del almacenamiento se configurarán en otra parte y no se deberán definir en este archivo.

Haga clic en link:https://github.com/netappeseries/beegfs/blob/master/getting_started/beegfs_on_netapp/gen2/host_vars/ictad22a01.yml["aquí"^] para obtener un ejemplo de un archivo de inventario completo que representa un solo nodo de bloque.



=== Mediante InfiniBand HDR (200 GB) o roce de 200 GB con nodos de bloque de EF600 de NetApp:

Para utilizar InfiniBand HDR (200 GB) con EF600, se debe configurar una segunda IP "virtual" para cada puerto físico. A continuación se muestra un ejemplo de la forma correcta de configurar un EF600 equipado con la HIC HDR InfiniBand de doble puerto:

[source, yaml]
----
eseries_controller_nvme_ib_port:
  controller_a:
    - 192.168.1.101   # Port 2a (virtual)
    - 192.168.2.101   # Port 2b (virtual)
    - 192.168.1.100   # Port 2a (physical)
    - 192.168.2.100   # Port 2b (physical)
  controller_b:
    - 192.168.3.101   # Port 2a (virtual)
    - 192.168.4.101   # Port 2b (virtual)
    - 192.168.3.100   # Port 2a (physical)
    - 192.168.4.100   # Port 2b (physical)
----