---
sidebar: sidebar 
permalink: custom/architectures-deploy-verify.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: Compruebe la implementación del sistema de archivos antes de colocar el sistema en producción. 
---
= Verifique la implementación de BeeGFS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Compruebe la implementación del sistema de archivos antes de colocar el sistema en producción.



== Descripción general

Antes de poner el sistema de archivos BeeGFS en producción, realice algunas comprobaciones de verificación.



=== Pasos

. Inicie sesión en cualquier cliente y ejecute lo siguiente para garantizar que todos los nodos esperados estén presentes o sean accesibles, no se han notificado inconsistencias ni otros problemas:
+
[source, bash]
----
beegfs-fsck --checkfs
----
. Apague todo el clúster y, a continuación, reinícielo. Desde cualquier nodo de archivo ejecute lo siguiente:
+
[source, bash]
----
pcs cluster stop --all # Stop the cluster on all file nodes.
pcs cluster start --all  # Start the cluster on all file nodes.
pcs status # Verify all nodes and services are started and no failures are reported (the command may need to be reran a few times to allow time for all services to start).
----
. Coloque cada nodo en espera y compruebe que los servicios de BeeGFS pueden conmutar por error a nodos secundarios. Para realizar este inicio de sesión en cualquiera de los nodos de archivo y ejecute lo siguiente:
+
[source, bash]
----
pcs status # Verify the cluster is healthy at the start.
pcs node standby <FILE NODE HOSTNAME> # Place the node under test in standby.
pcs status # Verify services are started on a secondary node and no failures are reported.
pcs node unstandby <FILE NODE HOSTNAME> # Take the node under test out of standby.
pcs status # Verify the file node is back online and no failures are reported.
pcs resource relocate run # Move all services back to their preferred nodes.
pcs status # Verify services have moved back to the preferred node.
----
. Utilizar herramientas de evaluación del rendimiento como IOR y MDTest para verificar que el rendimiento del sistema de archivos cumple las expectativas. Se pueden encontrar ejemplos de pruebas y parámetros comunes utilizados con BeeGFS link:../second-gen/beegfs-design-solution-verification.html["Verificación del diseño"^]en la  sección de BeeGFS on NetApp Verified Architecture.


Las pruebas adicionales deben realizarse en función de los criterios de aceptación definidos para una instalación/emplazamiento particular.
