---
sidebar: sidebar 
permalink: custom/architectures-setup-ansible-control-node.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: Configure un nodo de control de Ansible para poner en marcha y gestionar el sistema de archivos. 
---
= Configure el nodo de control de Ansible
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Configure un nodo de control de Ansible para poner en marcha y gestionar el sistema de archivos.



== Descripción general

Un nodo de control de Ansible es una máquina física o virtual Linux que se usa para gestionar el clúster. Debe cumplir los siguientes requisitos:

* Cumpla el link:../second-gen/beegfs-technology-requirements.html#ansible-control-node-requirements["requisitos"^]rol de alta disponibilidad de BeeGFS, incluidas las versiones instaladas de Ansible, Python y cualquier otro paquete de Python adicional.
* Conozca al funcionario link:https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#control-node-requirements["Requisitos del nodo de control de Ansible"^] incluye las versiones del sistema operativo.
* Tienen acceso SSH y HTTPS a todos los nodos de archivos y bloques.


Se pueden encontrar pasos de instalación detalladoslink:../second-gen/beegfs-deploy-setting-up-an-ansible-control-node.html["aquí"^].
