---
sidebar: sidebar 
permalink: custom-architectures-deploy-playbook-overview.html 
keywords: BeeGFS on NetApp, NetApp Custom Architectures, EF600 
summary: Puesta en marcha y gestión de clústeres de alta disponibilidad de BeeGFS mediante Ansible. 
---
= Descripción general del libro de estrategia de Ansible
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puesta en marcha y gestión de clústeres de alta disponibilidad de BeeGFS mediante Ansible.



== Descripción general

En las secciones anteriores se han realizado los pasos necesarios para crear un inventario de Ansible que represente un clúster de alta disponibilidad de BeeGFS. En esta sección se presenta la automatización de Ansible desarrollada por NetApp para poner en marcha y gestionar el clúster.



== Ansible: Conceptos clave

Antes de continuar, es útil estar familiarizado con algunos conceptos clave de Ansible:

* Las tareas que se deben ejecutar con un inventario de Ansible se definen en lo que se conoce como *playbook*.
+
** La mayoría de las tareas en Ansible están diseñadas para ser *idempotente*, lo que significa que pueden ejecutarse varias veces para verificar que la configuración/estado deseada todavía se aplica sin romper las cosas ni hacer actualizaciones innecesarias.


* La unidad más pequeña de ejecución en Ansible es un *módulo*.
+
** Los libros de estrategia habituales utilizan varios módulos.
+
*** Ejemplos: Descargue un paquete, actualice un archivo de configuración, inicie/habilite un servicio.


** NetApp distribuye módulos para automatizar los sistemas E-Series de NetApp.


* La automatización compleja se empaquetará mejor como rol.
+
** Básicamente, un formato estándar para distribuir un libro de aplicaciones reutilizable.
** NetApp distribuye roles para hosts Linux y sistemas de archivos BeeGFS.






== Rol de ha de BeeGFS para Ansible: Conceptos clave

Toda la automatización necesaria para poner en marcha y gestionar cada versión de BeeGFS en NetApp se presenta como un rol de Ansible y se distribuye como parte de la link:https://galaxy.ansible.com/netapp_eseries/beegfs["Colección de Ansible E-Series de NetApp para BeeGFS"^]:

* Este papel se puede considerar como un lugar entre un motor de *instalador* y un motor de *implementación/administración* moderno para BeeGFS.
+
** Aplica una infraestructura moderna como prácticas de código y filosofías para simplificar la gestión de infraestructura de almacenamiento a cualquier escala.
** Similar a cómo link:https://kubernetes.io/docs/setup/production-environment/tools/kubespray/["Kubespray"^] El proyecto permite a los usuarios poner en marcha/mantener una distribución completa de Kubernetes para la infraestructura informática de escalado horizontal.


* Este rol es el formato *definido por software* que utiliza NetApp para empaquetar, distribuir y mantener BeeGFS en soluciones NetApp.
+
** Esforzarse por crear una experiencia “similar a un dispositivo” sin necesidad de distribuir una distribución entera de Linux o una imagen grande.
** Incluye agentes de recursos en clúster compatibles con Open Cluster Framework (OCF) de NetApp para objetivos BeeGFS personalizados, direcciones IP y supervisión que proporcionan una integración inteligente con Pacemaker/BeeGFS.


* Esta función no se limita a la puesta en marcha de la «automatización», sino que está destinada a gestionar todo el ciclo de vida del sistema de archivos, incluidos:
+
** Aplicar cambios y actualizaciones de configuración por servicio o para todo el clúster.
** Automatizar la reparación y recuperación del clúster después de resolver problemas de hardware.
** Simplificación del ajuste del rendimiento con valores predeterminados establecidos en función de amplias pruebas con BeeGFS y volúmenes de NetApp.
** Verificación y corrección de deriva de configuración.




NetApp también proporciona un rol de Ansible para link:https://github.com/netappeseries/beegfs/tree/master/roles/beegfs_client["Clientes de BeeGFS"^], Que se puede utilizar opcionalmente para instalar BeeGFS y montar sistemas de archivos en nodos de cálculo/GPU/inicio de sesión.
